### ISSUE TITLE
libportabe

### ISSUE THREAD

**Issue by lostzombie** [wvxwxvw/LibPortablePlus#2]
попробовал допилить libportabe:
1. добавил хуки (редирект) для папок ProgramData, LocalLow
2. добавил хук (запрет) на создание веток реестра (не работает через dependentlib.list, только через инъекцию в mozglue.dll)

если интересно, то как связаться (не хочу выкладывать непротестированное досконально)

**Comment by lostzombie** [comment]
нет не правил dll, просто добавил хук на папки по аналогии с LocalAppData на ещё две папки и добавил хуки на функции CreateRegExW, SetRegValueW. Просто смущает факт, что авторы оригинала этого не сделали за долгое время существования либ, возможно я не до конца разбираюсь в кухне Firefox и лишь хотел выслать результат на тест, кому-то кто больше разбирается в вопросе, на предмет имеет ли всё это смысл и корректен ли результат. Возможно попробую оформить корректный форк.

**Comment by wvxwxvw** [comment]
Я не умею компилировать, так что без dll ничем помочь не могу, а с dll могу помочь только тестом.
Пишите,, если что, по тому адресу что я вам дал.

**Comment by lostzombie** [comment]
> Пишите,, если что, по тому адресу что я вам дал.

или я туплю под вечер или не достаточно освоился на гитхаб но совсем не понял куда писать и где вы дали адрес))

**Comment by lostzombie** [comment]
> Пишите,, если что, по тому адресу что я вам дал.
эм, немного не понял где и какой вы адрес дали.

**Comment by wvxwxvw** [comment]
@lostzombie 
А он был. ) Подумайте. Не буду же я его в открытую здесь писать.

**Comment by lostzombie** [comment]
квесты не моё, https://t.me/lz57005

**Comment by wvxwxvw** [comment]
Но вы всегда можете свой адрес дать и я вам напишу.

**Comment by wvxwxvw** [comment]
Телеграма у меня нет.
