### ISSUE TITLE
Ошибка во время запуска

### ISSUE THREAD

**Issue by Andreyserg3** [wvxwxvw/LibPortablePlus#3]
Win10 X64 1903 (порезанная ntlite'ом)
При запуске FiREF0X.exe (никакие изменения не вносил, только распаковал программу)
{Всплывающее окно приложения: firefox.exe - Ошибка приложения : Инструкция по адресу 0x00000000733C432A обратилась к памяти по адресу 0x0000000000000000. Память не может быть read.}

**Comment by wvxwxvw** [comment]
Сочувствую. Только при чем тут я? У меня в сборке никаких FiREF0X.exe нет и никогда не было.
